swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8081
basePath: /
tags:
  - name: basic-error-controller
    description: Basic Error Controller
  - name: temperatura-controller
    description: Temperatura Controller
paths:
  /error:
    get:
      tags:
        - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingGET
      produces:
        - text/html
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    head:
      tags:
        - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingHEAD
      consumes:
        - application/json
      produces:
        - text/html
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    post:
      tags:
        - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPOST
      consumes:
        - application/json
      produces:
        - text/html
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    put:
      tags:
        - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPUT
      consumes:
        - application/json
      produces:
        - text/html
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    delete:
      tags:
        - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingDELETE
      produces:
        - text/html
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    options:
      tags:
        - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingOPTIONS
      consumes:
        - application/json
      produces:
        - text/html
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
    patch:
      tags:
        - basic-error-controller
      summary: errorHtml
      operationId: errorHtmlUsingPATCH
      consumes:
        - application/json
      produces:
        - text/html
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelAndView'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /temperatura:
    get:
      tags:
        - temperatura-controller
      summary: buscaTemperaturasPorCoordenada
      operationId: buscaTemperaturasPorCoordenadaUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/TemperaturaJanelaDto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - temperatura-controller
      summary: registrarTemperatura
      operationId: registrarTemperaturaUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: temperatura
          description: temperatura
          required: true
          schema:
            $ref: '#/definitions/TemperaturaModel'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TemperaturaModel'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/delete:
    delete:
      tags:
        - temperatura-controller
      summary: apagarBanco
      operationId: apagarBancoUsingDELETE
      produces:
        - '*/*'
      parameters:
        - in: body
          name: key
          description: key
          required: true
          schema:
            $ref: '#/definitions/Key'
      responses:
        '200':
          description: OK
          schema:
            type: object
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /temperatura/folhaDeRosto:
    get:
      tags:
        - temperatura-controller
      summary: gerarFolhaDeRosto
      operationId: gerarFolhaDeRostoUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EstatisticaModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/folhaDeRostoCSV:
    get:
      tags:
        - temperatura-controller
      summary: gerarFolhadeRostoCSV
      operationId: gerarFolhadeRostoCSVUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/janelas:
    get:
      tags:
        - temperatura-controller
      summary: gerarJanelas
      operationId: gerarJanelasUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/JanelasModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/mediaGeral:
    get:
      tags:
        - temperatura-controller
      summary: mediaGeral
      operationId: mediaGeralUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EstatisticaModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/mediaJanelas:
    get:
      tags:
        - temperatura-controller
      summary: mediaDasJanelas
      operationId: mediaDasJanelasUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EstatisticaModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/oscilacao:
    get:
      tags:
        - temperatura-controller
      summary: oscilacao
      operationId: oscilacaoUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/RampaModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/rampaSubida:
    get:
      tags:
        - temperatura-controller
      summary: rampaSubida
      operationId: rampaSubidaUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/RampasModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/temperaturasCSV:
    get:
      tags:
        - temperatura-controller
      summary: getAllEmployeesInCsv
      operationId: getAllEmployeesInCsvUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /temperatura/{dataString}:
    get:
      tags:
        - temperatura-controller
      summary: buscaUltimasTemperaturas
      operationId: buscaUltimasTemperaturasUsingGET
      produces:
        - '*/*'
      parameters:
        - name: dataString
          in: path
          description: dataString
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TemperaturaModel'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
definitions:
  EstatisticaModel:
    type: object
    properties:
      media:
        type: number
        format: double
      temperaturaCorrigida:
        type: number
        format: double
      termopar_1:
        type: number
        format: double
      termopar_2:
        type: number
        format: double
      termopar_3:
        type: number
        format: double
      termopar_amb:
        type: number
        format: double
    title: EstatisticaModel
  JanelasModel:
    type: object
    properties:
      valorFinal:
        type: integer
        format: int32
      valorInicial:
        type: integer
        format: int32
    title: JanelasModel
  Key:
    type: object
    properties:
      key:
        type: string
    title: Key
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
          - ACCEPTED
          - ALREADY_REPORTED
          - BAD_GATEWAY
          - BAD_REQUEST
          - BANDWIDTH_LIMIT_EXCEEDED
          - CHECKPOINT
          - CONFLICT
          - CONTINUE
          - CREATED
          - DESTINATION_LOCKED
          - EXPECTATION_FAILED
          - FAILED_DEPENDENCY
          - FORBIDDEN
          - FOUND
          - GATEWAY_TIMEOUT
          - GONE
          - HTTP_VERSION_NOT_SUPPORTED
          - IM_USED
          - INSUFFICIENT_SPACE_ON_RESOURCE
          - INSUFFICIENT_STORAGE
          - INTERNAL_SERVER_ERROR
          - I_AM_A_TEAPOT
          - LENGTH_REQUIRED
          - LOCKED
          - LOOP_DETECTED
          - METHOD_FAILURE
          - METHOD_NOT_ALLOWED
          - MOVED_PERMANENTLY
          - MOVED_TEMPORARILY
          - MULTIPLE_CHOICES
          - MULTI_STATUS
          - NETWORK_AUTHENTICATION_REQUIRED
          - NON_AUTHORITATIVE_INFORMATION
          - NOT_ACCEPTABLE
          - NOT_EXTENDED
          - NOT_FOUND
          - NOT_IMPLEMENTED
          - NOT_MODIFIED
          - NO_CONTENT
          - OK
          - PARTIAL_CONTENT
          - PAYLOAD_TOO_LARGE
          - PAYMENT_REQUIRED
          - PERMANENT_REDIRECT
          - PRECONDITION_FAILED
          - PRECONDITION_REQUIRED
          - PROCESSING
          - PROXY_AUTHENTICATION_REQUIRED
          - REQUESTED_RANGE_NOT_SATISFIABLE
          - REQUEST_ENTITY_TOO_LARGE
          - REQUEST_HEADER_FIELDS_TOO_LARGE
          - REQUEST_TIMEOUT
          - REQUEST_URI_TOO_LONG
          - RESET_CONTENT
          - SEE_OTHER
          - SERVICE_UNAVAILABLE
          - SWITCHING_PROTOCOLS
          - TEMPORARY_REDIRECT
          - TOO_EARLY
          - TOO_MANY_REQUESTS
          - UNAUTHORIZED
          - UNAVAILABLE_FOR_LEGAL_REASONS
          - UNPROCESSABLE_ENTITY
          - UNSUPPORTED_MEDIA_TYPE
          - UPGRADE_REQUIRED
          - URI_TOO_LONG
          - USE_PROXY
          - VARIANT_ALSO_NEGOTIATES
      view:
        $ref: '#/definitions/View'
      viewName:
        type: string
    title: ModelAndView
  RampaModel:
    type: object
    properties:
      duracao:
        type: integer
        format: int64
      fim:
        type: string
        format: date-time
      inicio:
        type: string
        format: date-time
      media:
        type: number
        format: double
      rampaSubindo:
        type: boolean
      tempAmbiente:
        type: number
        format: double
      tempMaxima:
        type: number
        format: double
      tempMinima:
        type: number
        format: double
      termopar:
        type: string
    title: RampaModel
  RampasModel:
    type: object
    properties:
      rampaDescendo:
        $ref: '#/definitions/RampaModel'
      rampaSubindo:
        $ref: '#/definitions/RampaModel'
    title: RampasModel
  TemperaturaJanelaDto:
    type: object
    properties:
      linha:
        type: integer
        format: int32
      termopar_1:
        type: number
        format: float
      termopar_2:
        type: number
        format: float
      termopar_3:
        type: number
        format: float
      termopar_amb:
        type: number
        format: float
    title: TemperaturaJanelaDto
  TemperaturaModel:
    type: object
    properties:
      dt_leitura:
        type: string
        format: date-time
      r:
        type: integer
        format: int32
      termopar_1:
        type: number
        format: float
      termopar_2:
        type: number
        format: float
      termopar_3:
        type: number
        format: float
      termopar_amb:
        type: number
        format: float
      x:
        type: integer
        format: int32
      'y':
        type: integer
        format: int32
      z:
        type: integer
        format: int32
    title: TemperaturaModel
  View:
    type: object
    properties:
      contentType:
        type: string
    title: View
