openapi: 3.0.0
info:
  version: 0.1.5
  title: Software de testes
  description: Projeto para o 3º semestre do CT Desenvolvimento de Sistemas. <br>Software para gerenciamento de mesa inteligente desenvolvida para a empresa TAIFF.
  
servers:
  - url: http://localhost:8080
    description: Servidor para o consumo dos end-points
    
paths:
  /teste/:
    post:
      tags:
      - 'Testes'
      summary: 'Cria um novo teste'
      description: 'Cria um novo teste'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/testePost'
      responses:
        '201':
          description: Teste criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/respostaTestePost'
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
    get:
      tags:
        - "Testes"
      summary: "Busca todos os testes"
      description: "Busca todos os testes"
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testesArray'
        '404':           
          description: Não encontrado
        '500':
          description: Falha na comunicação com o servidor  

  /teste/{modelo}:
    get:
      tags:
        - "Testes"
      summary: "Busca os testes pelo MODELO do produto"
      description: "Busca os testes pelo MODELO do produto"
      parameters:
        - name: modelo
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: string
            format: utf-8
            minimum: 1
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testesArray'
        '404':           
          description: Não encontrado
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
  /teste/id/{id_teste}:
    get:
      tags:
        - "Testes"
      summary: "Busca o teste pelo ID do teste"
      description: "Busca um teste em especifico pelo ID do teste"
      parameters:
        - name: id_teste
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type: string
            format: utf-8
            minimum: 1
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/testes'
        '404':           
          description: Não encontrado
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
  /teste/{id_teste}:
    put:
      tags:
      - 'Testes'
      summary: 'Edita um teste existente'
      description: 'Edita um teste existente'
      parameters:
        - name: id_teste
          in: path
          required: true
          description: Id do teste a ser excluído.
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/testes'
      responses:
        '200':
          description: OK
        '404':           
          description: Não encontrado
        '400':
          description: Valor inválido
        '500':
          description: Falha na comunicação com o servidor
          
    delete:
      tags:
        - "Testes"
      summary: "Deletar teste pelo ID do teste"
      description: "Deletar teste pelo ID do teste"
      parameters:
        - name: id_teste
          in: path
          required: true
          description: Id do teste a ser excluído.
          schema:
            type: integer
            format: int64
      responses: 
        '200':
          description: OK
        '404':           
          description: Não encontrado
        '500':
          description: Falha na comunicação com o servidor

components:
  schemas:
    testesArray:
      type: object
      properties:
        testes:
          type: array
          items:
            $ref: '#/components/schemas/testes'
            
    coordenadasZeroPeca:
      type: object
      properties:
        teste_id:
          type: integer
          format: int64
          example: 321412
        x:
          type: integer
          format: int64
          example: 30
        y:
          type: integer
          format: int64
          example: 55
        z:
          type: integer
          format: int64
          example: 15
      
            
    coordenadas:
      type: object
      properties:
        teste_id:
          type: integer
          format: int64
          example: 321412
        x:
          type: integer
          format: int64
          example: 30
        y:
          type: integer
          format: int64
          example: 55
        z:
          type: integer
          format: int64
          example: 15
        r:
          type: integer
          format: int64
          example: 25
        t:
          type: integer
          format: int64
          example: 45
          
    
    testes:
      type: object
      properties:
        id_teste:
          type: integer
          format: int64
          example: 321412
        nome_teste:
          type: string
          format: utf-8
          example: teste-de-temperatura
        modelo:
          type: string
          format: utf-8
          example: modelo-produto
        coordenadas:
          type: array
          items:
            $ref: '#/components/schemas/coordenadas'
        zero_peca: 
          type: object
          $ref: '#/components/schemas/coordenadasZeroPeca'
          
    testePost:
      type: object
      properties:
        modelo:
          type: string
          format: utf-8
          example: modelo produto
        nome_teste:
          type: string
          format: utf-8
          example: modelo produto - T1
          
    respostaTestePost:
      type: object
      properties:
        id_teste:
          type: integer
          format: int64
          example: 1
        nome_teste:
          type: string
          format: utf-8
          example: teste-de-temperatura
        modelo:
          type: string
          format: utf-8
          example: modelo-produto
        coordenadas:
          example: null
        zero_peca: 
          example: null